# Generated by Django 5.1.3 on 2024-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_user', '0002_remove_telegramuser_count_call_calltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
